// Generated by CoffeeScript 1.5.0
var DRONE;

DRONE = DRONE || {};

DRONE.Translator = (function() {
  var commandMap, notSupportedError, processMessage;
  commandMap = {
    takeoff: function() {
      return DRONE.API.takeOff();
    },
    land: function() {
      return DRONE.API.land();
    }
  };
  processMessage = function(msg) {
    return commandMap[msg].call();
  };
  notSupportedError = function(msg) {
    var command, fn;
    return console.log("" + msg + " is not supported, try one of these commands [" + ((function() {
      var _results;
      _results = [];
      for (command in commandMap) {
        fn = commandMap[command];
        _results.push(command);
      }
      return _results;
    })()) + "]");
  };
  return {
    translate: function(opts) {
      var msg;
      msg = opts.msg;
      if (commandMap[msg] == null) {
        return typeof opts.error === "function" ? opts.error(notSupportedError(msg)) : void 0;
      }
      processMessage(msg);
      return typeof opts.success === "function" ? opts.success() : void 0;
    }
  };
})();
