// Generated by CoffeeScript 1.5.0
var DRONE;

DRONE = DRONE || {};

DRONE.Translator = (function() {
  var commandMap, notSupportedError, processMessage;
  commandMap = {
    takeoff: function() {
      return DRONE.API.takeoff();
    },
    land: function() {
      return DRONE.API.land();
    }
  };
  processMessage = function(msg) {
    return commandMap[msg].call();
  };
  notSupportedError = function(msg) {
    var command, fn;
    return console.log("" + msg + " is not supported, try one of these commands [" + ((function() {
      var _results;
      _results = [];
      for (command in commandMap) {
        fn = commandMap[command];
        _results.push(command);
      }
      return _results;
    })()) + "]");
  };
  return {
    translate: function(msg) {
      if (commandMap[msg] == null) {
        return notSupportedError(msg);
      }
      return processMessage(msg);
    }
  };
})();
