// Generated by CoffeeScript 1.5.0
var DRONE;

DRONE = DRONE || {};

DRONE.TweetQueue = (function() {
  var cancel, main, queue, running, speed;
  queue = [];
  running = false;
  speed = 3000;
  cancel = function() {
    if (running) {
      clearInterval(running);
      return running = false;
    }
  };
  main = function() {
    return Notifications.notify('success', 'Started!');
  };
  if (!running) {
    running = true;
    running = setInterval(function() {
      var msg, opts, result;
      msg = queue.pop();
      if (msg) {
        opts = {
          msg: msg,
          error: function() {
            return Notifications.droneAction('error', "Error performing " + msg + ", not supported");
          },
          success: function() {
            return Notifications.droneAction('success', "Performing " + msg);
          }
        };
        return result = DRONE.Translator.translate(opts);
      }
    }, speed);
  }
  return {
    init: function() {
      $('#start').bind('click', main);
      return $('#cancel').bind('click', cancel);
    },
    push: function(item) {
      return queue.push(item);
    }
  };
})();
