// Generated by CoffeeScript 1.5.0
var DRONE;

DRONE = DRONE || {};

DRONE.TweetQueue = (function() {
  var interval, queue, running, speed;
  queue = [];
  interval = null;
  running = false;
  speed = 3000;
  return {
    cancel: function() {
      if (running) {
        clearInterval(running);
        return running = false;
      }
    },
    main: function() {
      if (!running) {
        running = true;
        interval = setInterval(function() {
          var msg, opts, result;
          item = queue.pop();
          var cmd = item['cmd'];
          command = cmd.cmd;

          if (command) {
            opts = {
              cmd: command,
              args: cmd.args,
              error: function() {
                return Notifications.droneAction('error', "Error performing " + command + ", not supported", item['meta']);
              },
              success: function() {
                return Notifications.droneAction('success', "Performing " + command, item['meta']);
              }
            };
            return result = DRONE.Translator.translate(opts);
          }
        }, speed);
      }
    },
    push: function(item) {
      return queue.push(item);
    }
  };
})();
